---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          path: 'Samuel/*'
          type: 'zip'
          filename: 'Samuel.zip'
      
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Samuel.zip"
          toke: ${{ secrets.GITHUB_TOKEN }}